# This is a basic workflow to help you get started with Actions

name: CI

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  workflow_dispatch:

jobs: 
  build:    
    runs-on: ubuntu-latest   
    steps:      
      - uses: actions/checkout@v3      
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:                  
          username: ${{secrets.DOCKERHUB_USER}}          
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: | 
            orbite82/kube-news:latest
            orbite82/kube-news:${{github.run_number}}
